Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -51,41 +51,43 @@ jobs:
           echo '[*] Installing build dependencies...'
           yum install -y gcc openssl-devel bzip2-devel libffi-devel make wget postgresql-devel zlib-devel readline-devel
 
-          echo '[*] Installing Python 3.9...'
+          echo '[*] Building Python 3.9 with shared library support...'
           cd /tmp
           wget -q https://www.python.org/ftp/python/3.9.18/Python-3.9.18.tgz
-          tar -xzf Python-3.9.18.tgz && cd Python-3.9.18
-          ./configure --enable-optimizations --prefix=/usr/local
+          tar -xzf Python-3.9.18.tgz
+          cd Python-3.9.18
+          ./configure --enable-optimizations --enable-shared --prefix=/usr/local
           make -j2 && make altinstall
+          echo '/usr/local/lib' > /etc/ld.so.conf.d/python3.9.conf
+          ldconfig
           ln -sf /usr/local/bin/python3.9 /usr/bin/python
           ln -sf /usr/local/bin/pip3.9 /usr/bin/pip
+          export LD_LIBRARY_PATH=/usr/local/lib
           python --version
+          ls -l /usr/local/lib | grep libpython || (echo '[!] libpython shared library missing!' && exit 1)
 
           echo '[*] Installing Python dependencies...'
           pip install --upgrade pip wheel setuptools
           pip install pyinstaller fastapi uvicorn sqlalchemy asyncpg jinja2 colorama psycopg2-binary
 
-          echo '[*] Verifying repo contents...'
-          ls -R /src/cygor || (echo '[!] cygor directory missing!' && exit 1)
-          cd /src
-
+          echo '[*] Building single-file binary...'
+          cd /src/cygor
           STATIC_PATH_ARG=''
-          if [ -d 'cygor/webapp/static' ]; then
-            STATIC_PATH_ARG='--add-data cygor/webapp/static:cygor/webapp/static'
+          if [ -d 'webapp/static' ]; then
+            STATIC_PATH_ARG='--add-data webapp/static:webapp/static'
           fi
 
-          echo '[*] Building single-file binary from cygor/cli.py...'
-          cd cygor
           pyinstaller --onefile --clean --noconfirm \
             --add-data 'webapp/templates:webapp/templates' \
             \$STATIC_PATH_ARG \
             --name cygor cli.py
 
-          echo '[*] Build complete, packaging...'
+          echo '[*] Packaging binary...'
           cd dist && chmod +x cygor
           tar -czf /src/${{ matrix.artifact_name }}.tar.gz cygor
           echo '[✓] Done building ${{ matrix.artifact_name }}'
           "
+
 
 
       - uses: actions/upload-artifact@v4
